DROP TABLE IF EXISTS scheduling_appointment_allocations CASCADE;
DROP TABLE IF EXISTS scheduling_slots CASCADE;

CREATE TABLE IF NOT EXISTS scheduling_slots (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id INT NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  capacity INT NOT NULL,
  booked_count INT NOT NULL,
  status VARCHAR(20) NOT NULL,
  CONSTRAINT uk_scheduling_slot_vet_time UNIQUE (vet_id, start_time)
);

CREATE TABLE IF NOT EXISTS scheduling_appointment_allocations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id INT NOT NULL UNIQUE,
  slot_id INT NOT NULL REFERENCES scheduling_slots (id)
);
