DROP TABLE IF EXISTS vet_specialties CASCADE;
DROP TABLE IF EXISTS visits CASCADE;
DROP TABLE IF EXISTS pets CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS types CASCADE;
DROP TABLE IF EXISTS specialties CASCADE;
DROP TABLE IF EXISTS vets CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS vets (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name  TEXT
);
CREATE INDEX IF NOT EXISTS idx_vets_last_name ON vets (last_name);

CREATE TABLE IF NOT EXISTS specialties (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);
CREATE INDEX IF NOT EXISTS idx_specialties_name ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
    vet_id       INT NOT NULL REFERENCES vets (id),
    specialty_id INT NOT NULL REFERENCES specialties (id),
    UNIQUE (vet_id, specialty_id)
);
CREATE INDEX IF NOT EXISTS idx_vet_spec_by_specialty ON vet_specialties (specialty_id, vet_id);

CREATE TABLE IF NOT EXISTS types (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);
CREATE INDEX IF NOT EXISTS idx_types_name ON types (name);

CREATE TABLE IF NOT EXISTS owners (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name  TEXT,
    address    TEXT,
    city       TEXT,
    telephone  TEXT
);
CREATE INDEX IF NOT EXISTS idx_owners_lastname_lower ON owners (lower(last_name));

CREATE TABLE IF NOT EXISTS pets (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT,
    birth_date DATE,
    type_id    INT NOT NULL REFERENCES types (id),
    owner_id   INT REFERENCES owners (id)
);
CREATE INDEX IF NOT EXISTS idx_pets_owner_lowername ON pets (owner_id, lower(name));
CREATE INDEX IF NOT EXISTS idx_pets_type ON pets (type_id);

CREATE TABLE IF NOT EXISTS visits (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id      INT REFERENCES pets (id),
    visit_date  DATE,
    description TEXT
);
CREATE INDEX IF NOT EXISTS idx_visits_pet_date_desc ON visits (pet_id, visit_date DESC);
CREATE INDEX IF NOT EXISTS idx_visits_date ON visits (visit_date);

CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(20) NOT NULL,
    password VARCHAR(60) NOT NULL,
    enabled  BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT pk_users PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    role VARCHAR(20) NOT NULL,
    FOREIGN KEY (username) REFERENCES users (username),
    CONSTRAINT uni_username_role UNIQUE (role, username)
);
CREATE INDEX IF NOT EXISTS idx_roles_username ON roles (username);
