DROP TABLE IF EXISTS vet_specialties CASCADE;
DROP TABLE IF EXISTS visits CASCADE;
DROP TABLE IF EXISTS pets CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS types CASCADE;
DROP TABLE IF EXISTS specialties CASCADE;
DROP TABLE IF EXISTS vets CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(20) NOT NULL,
    password VARCHAR(60) NOT NULL,
    enabled  BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT pk_users PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS vets (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name  TEXT,
    email      TEXT,
    username   VARCHAR(20) UNIQUE,
    CONSTRAINT fk_vet_user FOREIGN KEY (username) REFERENCES users(username)
);
CREATE INDEX IF NOT EXISTS idx_vets_last_name ON vets (last_name);

CREATE TABLE IF NOT EXISTS specialties (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);
CREATE INDEX IF NOT EXISTS idx_specialties_name ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
    vet_id       INT NOT NULL REFERENCES vets (id),
    specialty_id INT NOT NULL REFERENCES specialties (id),
    UNIQUE (vet_id, specialty_id)
);
CREATE INDEX IF NOT EXISTS idx_vet_spec_by_specialty ON vet_specialties (specialty_id, vet_id);

CREATE TABLE IF NOT EXISTS types (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);
CREATE INDEX IF NOT EXISTS idx_types_name ON types (name);

CREATE TABLE IF NOT EXISTS owners (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name  TEXT,
    address    TEXT,
    city       TEXT,
    telephone  TEXT UNIQUE,
    email      TEXT,
    username   VARCHAR(20) UNIQUE,
    CONSTRAINT fk_owner_user FOREIGN KEY (username) REFERENCES users(username)
);
CREATE INDEX IF NOT EXISTS idx_owners_lastname_lower ON owners (lower(last_name));

CREATE TABLE IF NOT EXISTS pets (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT,
    birth_date DATE,
    type_id    INT NOT NULL REFERENCES types (id),
    owner_id   INT REFERENCES owners (id)
);
CREATE INDEX IF NOT EXISTS idx_pets_owner_lowername ON pets (owner_id, lower(name));
CREATE INDEX IF NOT EXISTS idx_pets_type ON pets (type_id);

CREATE TABLE IF NOT EXISTS visits (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id      INT REFERENCES pets (id),
    visit_date  DATE,
    description TEXT,
    status      VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    vet_id      INT REFERENCES vets (id)
);
CREATE INDEX IF NOT EXISTS idx_visits_pet_date_desc ON visits (pet_id, visit_date DESC);
CREATE INDEX IF NOT EXISTS idx_visits_date ON visits (visit_date);
CREATE INDEX IF NOT EXISTS idx_visits_vet ON visits (vet_id);

CREATE TABLE IF NOT EXISTS appointments (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id     INT NOT NULL REFERENCES owners (id) ON DELETE CASCADE,
    pet_id       INT NOT NULL REFERENCES pets (id) ON DELETE CASCADE,
    start_time   TIMESTAMP NOT NULL,
    status       VARCHAR(20) NOT NULL,
    notes        TEXT,
    triage_notes TEXT,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    vet_id       INT REFERENCES vets (id),
    visit_id     INT UNIQUE REFERENCES visits (id)
);
CREATE INDEX IF NOT EXISTS idx_appointments_owner ON appointments (owner_id);
CREATE INDEX IF NOT EXISTS idx_appointments_pet ON appointments (pet_id);
CREATE INDEX IF NOT EXISTS idx_appointments_vet ON appointments (vet_id);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON appointments (status);

CREATE TABLE IF NOT EXISTS roles (
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    role     VARCHAR(20) NOT NULL,
    FOREIGN KEY (username) REFERENCES users (username),
    CONSTRAINT uni_username_role UNIQUE (role, username)
);
CREATE INDEX IF NOT EXISTS idx_roles_username ON roles (username);

CREATE TABLE IF NOT EXISTS scheduling_slots (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id INT NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  capacity INT NOT NULL,
  booked_count INT NOT NULL,
  status VARCHAR(20) NOT NULL,
  CONSTRAINT uk_scheduling_slot_vet_time UNIQUE (vet_id, start_time)
);

CREATE TABLE IF NOT EXISTS scheduling_appointment_allocations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id INT NOT NULL UNIQUE,
  slot_id INT NOT NULL REFERENCES scheduling_slots (id)
);
