DROP TABLE IF EXISTS notification_log;

CREATE TABLE IF NOT EXISTS notification_log (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  appointment_id INTEGER,
  event_type VARCHAR(50),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
